"""Fetch a balanced JudgeBench sample for hard-baseline evaluation.

JudgeBench (ICLR 2025) is built so judges struggle — objective response pairs
across knowledge/reasoning/math/coding where strong judges score near random.
Rows: (question, response_A, response_B, label) with label in {"A>B","B>A"}.
We normalize to {id, subset, question, chosen, rejected} (chosen = the correct
side per label). No model credits — just the dataset download.

Run: python scripts/fetch_judgebench_sample.py
"""

from __future__ import annotations

import json
import urllib.parse
import urllib.request
from pathlib import Path

DATASET = "ScalerLab/JudgeBench"
BASE = "https://datasets-server.huggingface.co/rows"
OUT = Path(__file__).resolve().parent.parent / "judy/data/datasets/judgebench_sample.jsonl"

SPLIT = "gpt"            # responses generated by GPT-4o (350 pairs)
OFFSETS = [0, 70, 140, 210, 280, 320]
PER_OFFSET = 14
PER_SUBSET_CAP = 10     # 'source' = subset (mmlu-pro, livebench-*, livecodebench)


def _fetch(offset: int, length: int) -> list[dict]:
    url = (f"{BASE}?dataset={urllib.parse.quote(DATASET)}&config=default"
           f"&split={SPLIT}&offset={offset}&length={length}")
    with urllib.request.urlopen(url, timeout=30) as resp:
        data = json.load(resp)
    out = []
    for r in data.get("rows", []):
        row = r["row"]
        label = str(row.get("label", "")).strip()
        if label not in ("A>B", "B>A"):
            continue  # skip ties / malformed
        a, b = row["response_A"], row["response_B"]
        chosen, rejected = (a, b) if label == "A>B" else (b, a)
        # coarse subject bucket from the source name (e.g. mmlu-pro-law -> mmlu-pro)
        source = str(row.get("source", "unknown"))
        subset = source.rsplit("-", 1)[0] if source.startswith("mmlu-pro") else source
        out.append({
            "id": f"jb-{row['pair_id'][:8]}",
            "subset": subset,
            "question": row["question"],
            "chosen": chosen,
            "rejected": rejected,
        })
    return out


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    by_subset: dict[str, list[dict]] = {}
    for off in OFFSETS:
        for r in _fetch(off, PER_OFFSET):
            bucket = by_subset.setdefault(r["subset"], [])
            if len(bucket) < PER_SUBSET_CAP:
                bucket.append(r)
    rows = [r for bucket in by_subset.values() for r in bucket]
    with OUT.open("w", encoding="utf-8") as fh:
        for r in rows:
            fh.write(json.dumps(r) + "\n")
    for subset, bucket in sorted(by_subset.items()):
        print(f"  {subset}: {len(bucket)}")
    print(f"Wrote {len(rows)} rows ({len(by_subset)} subsets) to {OUT}")


if __name__ == "__main__":
    main()
